apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-ui
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/KennethTaipe06/argocd-example-apps.git'
    targetRevision: HEAD
    path: guestbook
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
