apiVersion: batch/v1
kind: Job
metadata:
  name: delete-replicasets-job
  labels:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: delete-replicasets
        image: bitnami/kubectl:latest
        command: ["kubectl", "delete", "replicaset", "-l", "app=guestbook-ui"]
      restartPolicy: Never
  backoffLimit: 4
