apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
        argocd.argoproj.io/hook: PostSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: byvoxel/php_test:latest
        name: guestbook-ui #holi
        ports:
        - containerPort: 80 #holi 3#