apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: guestbook-ui-role
rules:
- apiGroups: ["apps"]
  resources: ["replicasets"]
  verbs: ["list", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guestbook-ui-rolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: guestbook-ui-role
  apiGroup: rbac.authorization.k8s.io
