apiVersion: batch/v1
kind: Job
metadata:
  name: guestbook-ui-cleanup
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: cleanup
        image: bitnami/kubectl:latest
        command: ["kubectl", "delete", "replicaset", "guestbook-ui-7d96d8dbb8"]
      restartPolicy: Never
  backoffLimit: 4
