apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: byvoxel/php_test:latest # Imagen de Docker utilizada para el despliegue
        name: guestbook-ui
        ports:
        - containerPort: 80
  strategy:
    type: Recreate
  hooks:
    - type: PostSync
      command: ["kubectl", "delete", "replicaset", "guestbook-ui-7d96d8dbb8"]
