apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - image: byvoxel/php_test:latest
        name: guestbook-ui #holi
        ports:
        - containerPort: 80 #holi 3#
---
apiVersion: batch/v1
kind: Job
metadata:
  name: delete-replicasets-job
  labels:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: delete-replicasets
        image: bitnami/kubectl:latest
        command: ["kubectl", "delete", "replicaset", "-l", "app=guestbook-ui"]
      restartPolicy: Never
  backoffLimit: 4
